export const channelFields = {
	facebook: {
		type: "Facebook Ad",
		play_name: "name",
		min_contacts: 100,
		fields: [
			{ label: "Start Date", value: "Planned_Start_Date__c", type: "date" },
			{ label: "End Date", value: "Planned_End_Date__c", type: "date" },
			{ label: "Primary Text", value: "Body_Text_Only__c", type: "html" },
			{ label: "Headline", value: "Subject__c", type: "html" },
			{ label: "Click URL", value: "Click_URL__c" },
			{ label: "Call to Action", value: "Call_To_Action__c" },
		],
		editFields: [
			{ label: "Play Name", keyLink: "name", name: "Name", type: "date", placeholder: "", id: "p__name", span: "col-span-6" },
			{ label: "Start Date", keyLink: "planned_start", name: "Planned_Start_Date__c", type: "date", placeholder: "", id: "p__planned-state-date", span: "col-span-3" },
			{ label: "End Date", keyLink: "planned_end", name: "Planned_End_Date__c", type: "date", placeholder: "", id: "p__planned-end-date", span: "col-span-3" },
			{ label: "Primary Text", keyLink: "body", name: "Body_Text_Only__c", type: "textarea", placeholder: "", id: "p__subject", span: "col-span-6" },
			{ label: "Headline", keyLink: "subject", name: "Subject__c", type: "text", placeholder: "", id: "p__body", span: "col-span-6" },
			{ label: "Click URL", keyLink: "click_url", name: "Click_URL__c", type: "url", placeholder: "", id: "p__click-url", span: "col-span-6" },
			{
				label: "Call to Action",
				keyLink: "call_to_action",
				name: "Call_To_Action__c",
				type: "select",
				placeholder: "",
				id: "p__call-to-action",
				span: "col-span-6",
				options: [
					{ value: "GET_PROMOTIONS", text: "Get Promotions", selected: false },
					{ value: "APPLY_NOW", text: "Apply Now", selected: false },
					{ value: "BOOK_TRAVEL", text: "Book Travel", selected: false },
					{ value: "CONTACT_US", text: "Contact Us", selected: false },
					{ value: "DONATE_NOW", text: "Donate Now", selected: false },
					{ value: "DOWNLOAD", text: "Download", selected: false },
					{ value: "GET_OFFER", text: "Get Offer Demo", selected: false },
					{ value: "GET_QUOTE", text: "Get Quote", selected: false },
					{ value: "GET_SHOWTIMES", text: "Get Showtimes", selected: false },
					{ value: "LEARN_MORE", text: "Learn More", selected: true },
					{ value: "LISTEN_NOW", text: "Listen Now", selected: false },
					{ value: "ORDER_NOW", text: "Order Now", selected: false },
					{ value: "PAY_TO_ACCESS", text: "Pay To Access", selected: false },
					{ value: "REQUEST_TIME", text: "Request Time", selected: false },
					{ value: "SEE_MENU", text: "See Menu", selected: false },
					{ value: "SEND_UPDATES", text: "Send Updates", selected: false },
					{ value: "SHOP_NOW", text: "Shop Now", selected: false },
					{ value: "SIGN_UP", text: "Sign Up", selected: false },
					{ value: "SUBSCRIBE", text: "Subscribe", selected: false },
					{ value: "WATCH_MORE", text: "Watch More", selected: false },
				],
			},
		],
	},
	marketingEmail: {
		type: "Marketing Email",
		play_name: "Marketing Email",
		min_contacts: 400,
		fields: [
			{ label: "Start Date", value: "Planned_Start_Date__c", type: "date" },
			{ label: "End Date", value: "Planned_End_Date__c", type: "date" },
			{ label: "Email Body", value: "Body_Text_Only__c", type: "html" },
			{ label: "Subject", value: "Subject__c", type: "html" },
		],
		editFields: [
			{ label: "Play Name", keyLink: "name", name: "Name", type: "date", placeholder: "", id: "p__name", span: "col-span-6" },
			{ label: "Start Date", keyLink: "planned_start", name: "Planned_Start_Date__c", type: "date", placeholder: "", id: "p__planned-state-date", span: "col-span-3" },
			{ label: "End Date", keyLink: "planned_end", name: "Planned_End_Date__c", type: "date", placeholder: "", id: "p__planned-end-date", span: "col-span-3" },
			{ label: "Email Body", keyLink: "body", name: "Body_Text_Only__c", type: "textarea", placeholder: "", id: "p__subject", span: "col-span-6" },
			{ label: "Subject", keyLink: "subject", name: "Subject__c", type: "text", placeholder: "", id: "p__body", span: "col-span-6" },
		],
	},
	linkedin: {
		type: "LinkedIn Ad",
		play_name: "name",
		fields: [
			{ label: "Start Date", value: "planned_start" },
			{ label: "End Date", value: "planned_end" },
			{ label: "Headline", value: "subject" },
			{ label: "Introductory Text", value: "body" },
			{ label: "Click URL", value: "click_url" },
			{ label: "Call to Action", value: "call_to_action" },
		],
	},
	editFields: [
		{ label: "Start Date", keyLink: "planned_start", name: "Planned_Start_Date__c", type: "date", placeholder: "", id: "p__planned-state-date", span: "col-span-3" },
		{ label: "End Date", keyLink: "planned_end", name: "Planned_End_Date__c", type: "date", placeholder: "", id: "p__planned-end-date", span: "col-span-3" },
		{ label: "Introductory Text", keyLink: "body", name: "Subject__c", type: "textarea", placeholder: "", id: "p__subject", span: "col-span-6" },
		{ label: "Headline", keyLink: "subject", name: "Body_Text_Only__c", type: "text", placeholder: "", id: "p__body", span: "col-span-6" },
		{ label: "Click URL", keyLink: "click_url", name: "Click_URL__c", type: "url", placeholder: "", id: "p__click-url", span: "col-span-6" },
		{
			label: "Call to Action",
			keyLink: "call_to_action",
			name: "Call_To_Action__c",
			type: "select",
			placeholder: "",
			id: "p__call-to-action",
			span: "col-span-6",
			options: [
				{ value: "APPLY", text: "Apply", selected: false },
				{ value: "ATTEND", text: "Attend", selected: false },
				{ value: "DOWNLOAD", text: "Download", selected: false },
				{ value: "JOIN", text: "Join", selected: false },
				{ value: "LEARN_MORE", text: "Learn More", selected: true },
				{ value: "REGISTER", text: "Register", selected: false },
				{ value: "REQUEST_DEMO", text: "Register Demo", selected: false },
				{ value: "SEE_MORE", text: "See More", selected: false },
				{ value: "SIGN_UP", text: "Sign Up", selected: false },
				{ value: "SUBSCRIBE", text: "Subscribe", selected: false },
				{ value: "VIEW_QUOTE", text: "View Quote", selected: false },
			],
		},
	],
};
